{% set name = "chebfun" %}
{% set version = "0.4.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chebpy/chebpy/archive/v{{ version }}.tar.gz
  sha256: 2122219456425a21f39a5787b5db7cfc8adcf63b37e692849593262b12c32164

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.16
    - pyfftw >=0.11

test:
  requires:
    - nose
    - python {{ python_min }}
  imports:
    - chebpy
  source_files:
    - tests/
  commands:
    - nosetests --where=tests/

about:
  home: https://github.com/chebpy/chebpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Python implementation of Chebfun
  description: |
    chebpy is a Python implementation of the popular MATLAB package
    Chebfun <http://chebfun.org>, allowing for computing with functions
    to near machine precision. It relies on polynomial interpolation
    using Chebyshev points and, through FFTs, expansions in Chebyshev
    polynomials.
  doc_url: https://github.com/chebpy/chebpy
  dev_url: https://github.com/chebpy/chebpy

extra:
  recipe-maintainers:
    - janniklasrose
    - markrichardson
